quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://ep-gentle-hill-acuqpqwr-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
quarkus.datasource.username=neondb_owner
quarkus.datasource.password=npg_Az2bqS8WlyGT
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.jdbc.min-size=1
quarkus.http.port=8081
